version: "3.1"

services: 
 db:
   image: mysql:5.7.27
   enviroment:
   MYSQL_DATABASE: cursa2019
   MYSQL_ROOT_PASSWORD: clave123
   ports:
   - 4000:3306
   volumes:
    -./mysqldata:/var/lib/mysql

    myadmin:
      image: phpmyadmin/phpmyadmin
      enviroment:
       PMA_HOST: db
       PHA_PORT: 3306
       PMA_PASSWORD: clave123
      ports: 
          - 8001:80

    app: 
      
      image: yiisofware/yii2-php:7.1-apache
      volumes:
         -./src/composer/cache:/root/.composer/cache:delegated
         -./src/basic:/app:delegated
         ports:   
           - 8000:80
                
         
         
 
